---
title: "Data prep"
output: html_notebook
---

```{r}
library(tidyverse)
library(magrittr)
library(haven)
library(car)
```


```{r}
maths <- read_dta("LCT Morroco/cct_aser_an.dta")
baseline <- read_dta("LCT Morroco/cct_baseline_an.dta")
indiv_baseline <- read_dta("LCT Morroco/cct_baseline_an.dta")
endline <- read_dta("LCT Morroco/cct_endline_an.dta")
school_baseline <- read_dta("LCT Morroco/cct_preliminary_survey_an.dta")
dropout <- read_dta('LCT Morroco/cct_school_visits_an.dta')
admin_data <- read_dta('LCT Morroco/cct_tayssir_admin_data_an.dta')
understanding <- read_dta("LCT Morroco/cct_knowledge_households_year1_an.dta")
```

```{r}
joined <- baseline %>%
  left_join(maths, by = "hhid", suffix = c("", ".y"))

# Process treatments
baseline %<>%
  mutate(schoolunitid = factor(schoolunitid),
         group_tvn = group,
         group1 = car::recode(group, "0 = NA;"),
         group = car::recode(group, "0 = NA; 1=1; 2:50 = 0")
         )

# Join with admin data
```

```{r}
# Get hhh variables
intermediate <- baseline %>%
  select(hhid, matches("^a[1-9]")) %>%
  gather(-hhid, key = "question", value = "value") %>%
  tidyr::separate(question, c("question", "person", "response"), sep = "_") 

more_intermediate <- intermediate %>%
  filter(question == 'a4' |
           question == 'a13' |
           (question == 'a15' & response == 1) |
           (question == 'a3' & is.na(response)) |
           question == 'a1'
           ) %>%
  select(-response) %>%
  spread(question, value)

temp <- more_intermediate %>%
  filter(a3 == 1) %>%
  select(hhid, a4, a13, a15)

```

```{r}
baseline$school_spending <- baseline %>%
  select(matches('^e[[:digit:]]')) %>%
  select(-ends_with('num')) %>%
  mutate_all(~.x %>% as.numeric %>% na_if(-99)) %>%
  rowSums(na.rm = T)
```


```{r}
week_to_month <- function (x) {
  (x / 7) * 30
}

year_to_month <- function (x) {
  x / 12
}


expenditure <- baseline %>%
  select(starts_with('h1_'),
         starts_with('h3_'),
         starts_with('h4_')
         ) %>%
  select_if(is.numeric) %>%
  mutate_at(
    vars(starts_with('h1_')),
    week_to_month
    ) %>%
  mutate_at(
    vars(starts_with('h4_')),
    week_to_month
    )

expenditure[expenditure < 0] <- 0

baseline$monthly_spending <- rowSums(expenditure, na.rm = TRUE) %>% log()

```

```{r}
num_kids <- baseline %>%
  select(hhid, matches("^d1_[0-9]{1,2}")) %>%
  gather(-hhid, key = "question", value = "value") %>%
  group_by(hhid) %>%
  dplyr::summarise(est_num_kids = sum(value == 1, na.rm = T))

```

https://docs.wfp.org/api/documents/WFP-0000022418/download/ for WI justifications

```{r}
assets <- baseline %>%
  select(b10_5, b10_6, b10_20, b10_26,  b10_21, b10_28, b4_1, b5_1, b9_5, monthly_spending) %>%
  mutate(b4_1 = car::recode(b4_1, "1:3 = 1; 4:5 = 2; -99 = NA"),
         b5_1 = car::recode(b5_1, "1:3 = 1; 5 = 1; 4 = 2; 6 = 2; -99 = NA"),
         b9_5 = car::recode(b9_5, "1 = 1; 2 = 2; -99:-1 = NA")
         )

assets[assets==-99]<-NA

# assets_wo_na <- 
```

```{r}
# standard_assets <- assets %>%
#   map_df(scale)
#   
# pca_results <- standard_assets %>%
#   as.matrix() %>%
#   bpca(1)
```

```{r}
joined$t6[maths$t6==0] <- 1
joined %<>% 
  mutate(maths_results = -(1-as.numeric(t6)) + (as.numeric(t5_2) / 2) + (as.numeric(t4_2) / 5) + (as.numeric(t3_2) / 5))
```

```{r}
# Not run yet
joined %<>%
  left_join(num_kids, by = "hhid") %>%
  left_join(temp, by = "hhid", multiple = "first")
  # filter(!duplicated(hhid))
```

```{r}
joined$school_spending <- baseline %>%
  select(matches('^e[[:digit:]]')) %>%
  select(-ends_with('num')) %>%
  mutate_all(~.x %>% as.numeric %>% na_if(-99)) %>%
  rowSums(na.rm = T)

joined$monthly_spending <- assets$monthly_spending
```

```{r}
# Join maths child details
joined$id_enf_test <- as.numeric(joined$id_enf_test)

joined <- more_intermediate %>%
  mutate(person = as.numeric(a1)) %>%
  right_join(joined, by = c("hhid", "person" = "id_enf_test"), suffix = c("_mc", "_hhh"), na_matches = "never")
```

```{r}
joined %<>%
    dplyr::rename(hhh_age = a13_hhh,
          hhh_gender = a4_hhh,
          hhh_literacy = a15_hhh,
          age = a13_mc,
          gender = a4_mc,
          group = group)
```

```{r}
joined %<>%
  left_join(understanding %>% select(ksm_c1_:ksm_c6_, hhid), by = "hhid") %>%
  mutate(no_understanding)

joined %<>%
  mutate(at_leisure = (c1_3_21_1 %>% as.character %>% substr(1,1)) %in% c('2','8'))
```

```{r}
joined_num <- joined %>%
#   mutate(cluster = as.factor(hhid)) %>%
  mutate(gender = factor(gender),
         hhid = as.factor(hhid),
         group = factor(group),
         benef = factor(benef)
         ) %>%
  mutate_at(vars(-hhid), as.numeric)
 
joined_num[joined_num < 0] <- NA
joined_num <- joined_num[complete.cases(joined_num[c('maths_results', 'group')]),]

joined_num %<>%
  select_if(function (x) !(length(x) == sum(is.na(x))))
```

```{r}
joined_num$school_spending <- joined_num$school_spending / joined_num$est_num_kids
```

```{r}
joined_num %<>%
  select(-t1:-t6, -id9_2:-im8, -group.y)
```

```{r}
joined_num %>% write_rds('morocco.rds')
```



