---
title: "Optimal tree work"
output: html_notebook
---

```{r}
library(tidyverse)
library(grf)
library(plyr)
library(policytree)
library(mlr)
morocco <- read_rds('morocco.rds')
```

```{r}
# Join on maths

maths$maths_results <- rowSums(maths[c('t6', 't5_1', 't4_1', 't3_1')])

two_outcome <- morocco %>%
  mutate(hhid = as.character(hhid)) %>%
  inner_join(maths %>% select(hhid, maths_results), by = "hhid") %>%
  mutate(maths_results_s = scale(maths_results) %>% as.numeric(),
         any_drops = scale(as.numeric(any_drops)) %>% as.numeric(),
         benef = factor(benef, 
                        levels = c("Mother", "Father")) %>% as.numeric(),
         gender = factor(gender, levels = c("F", "M")) %>% as.numeric(),
         ) %>%
  left_join(baseline %>% select(hhid)) %>%
  mutate(group = as_factor(group)) %>%
  mutate(hhid = as.factor(hhid)) %>%
  na.omit()

```

```{r}
X_vars <- two_outcome %>% select(hhh_gender, hhh_age, monthly_spending, hhh_literacy, age, gender, benef)

Y_vars <- two_outcome %>% select(maths_results_s, any_drops)
```


```{r}
cf.raw = multi_arm_causal_forest(
  X_vars %>% mutate_all(as.numeric), 
  Y_vars, 
  two_outcome$group,
  Y.hat = NULL ,
  W.hat = two_outcome$group %>% table %>% prop.table() %>% as.vector(),
  num.trees = 5000
  )

tau.hat = predict(cf.raw)$predictions %>% plyr::adply(1:3)
```

```{r}
# For maths
tau.hat %>%
  ggplot(aes(x = V1)) + geom_histogram() + facet_grid(X2 ~ X3)

ggsave('arm_ATEs.png', width = 4, height = 10)
```

## Export data for use in Python

```{r}
taus <- tau.hat %>% spread(X2,V1)
tau1 <- taus %>% filter(X3 == "any_drops") %>% select(-X1, -X3)
names(tau1) <- c("any_drops2-1", "any_drops3-1", "any_drops4-1")
tau2 <- taus %>% filter(X3 == "maths_results_s") %>% select(-X1, -X3)
names(tau2) <- c("maths2-1", "maths3-1", "maths4-1")
bind_cols(two_outcome, tau1, tau2) %>%
  write_csv("C:\\Users\\pbreh\\PycharmProjects\\OptimalPolicyMOBO\\train_data1.csv")
```

## Start fitting trees

```{r}
dt = sort(sample(nrow(two_outcome), nrow(two_outcome)*.5))
train<-two_outcome[dt,]
test<-two_outcome[-dt,]
```


```{r}
train_data <- bind_cols(tau.hat %>% 
                         filter(X2 == "3 - 1", X3 == "maths_results_s") %>% 
                         select(V1) %>% 
                         .[dt,],
                       train[X_vars] %>% mutate_all(as.numeric))

val_data <- bind_cols(tau.hat %>% 
                         filter(X2 == "3 - 1", X3 == "maths_results_s") %>% 
                         select(V1) %>% 
                         .[-dt,],
                       test[X_vars] %>% mutate_all(as.numeric))



tree_test <- rpart::rpart(V1 ~ ., data = test_data, control = list(maxdepth = 3))
rpart.plot::rpart.plot(tree_test, yesno = 2)
```

```{r}
start_time <- Sys.time()
pt <- policy_tree(train_data[X_vars], cbind(train_data['...1'], 0.1), depth = 3)
end_time <- Sys.time()
pt_time <- end_time - start_time
```

```{r}
start_time <- Sys.time()
ht <- hybrid_policy_tree(train_data[X_vars], cbind(train_data['...1'], 0.1), depth = 3, search.depth = 1)
ht_end_time <- Sys.time()
ht_time <- ht_end_time - start_time
```

```{r}
start_time <- Sys.time()
gt <- rpart::rpart(...1 ~ ., data = train_data, control = list(maxdepth = 3))
gt_end_time <- Sys.time()
gt_time <- gt_end_time - start_time
```

```{r}
get_utility <- function(predictions, gamma) {
  utilities <- c()
  for (i in 1:nrow(gamma)) utilities <- c(utilities, gamma[i, predictions[i]])
  surrogate_util <- mean(utilities)
  oracle_util <- gamma %>% apply(1, max) %>% mean()
  return(list(mean_utility = surrogate_util, oracle_utility = oracle_util, regret = oracle_util - surrogate_util))
}
```

```{r}
# Greedy tree translate

```


```{r}
pt_regret <- get_utility(predict(pt, val_data[X_vars]), cbind(val_data['...1'], 0.1))
ht_regret <- get_utility(predict(ht, val_data[X_vars]), cbind(val_data['...1'], 0.1))
gt_regret <- get_utility(
  ifelse(predict(ht, val_data[X_vars]) > 0.1, 1, 2), 
  cbind(val_data['...1'], 0.1))
```

```{r}
print("Policy tree")
pt_regret
print("Hybrid tree")
ht_regret
print("Greedy tree")
gt_regret
```

```{r}
pt_time
ht_time
gt_time
```

```{r}
get_oracles <- function(gamma1, gamma2, g1_weight) {
  # Get the weighted utility matrix
  gamma <- (gamma1 * g1_weight) + ((100.1 - g1_weight) * gamma2)

  # Find the maximum
  maxes <- max.col(gamma)

  # Calculate seperate utilities for the treatment
  g1_total <- c()
  for (i in 1:length(maxes)) g1_total <- c(g1_total , gamma1[i, maxes[i]])

  g2_total <- c()
  for (i in 1:length(maxes)) g2_total <- c(g2_total , gamma2[i, maxes[i]])

  return(list(g1 = g1_total, g2 = g2_total))

}
```


```{r}
honest_pt <- function(X, gamma1, gamma2, g1_weight) {
  # Add in mix of gammas for fitting
  gamma = (gamma1 * g1_weight) + ((100.1 - g1_weight) * gamma2)
  ht = policy_tree(X, gamma, depth = 3)

  png(filename="optimal.png")
  plot(ht)
  dev.off()
  return (ht)
}
```

```{r}
opt <- honest_pt(test_data[1:1500,X_vars], tau1[1:1500,], tau2[1:1500,], 99)
```



