---
title: "Paper 4"
output: html_notebook
---
# Set-up

```{r}
library(tidyverse)
library(magrittr)
library(grf)
library(readxl)
library(cowplot)

morocco <- read_rds('morocco.rds') %>%
  filter(group > 1) %>%
  mutate(group = group -1)

big_covars <- morocco %>% select(-hhid, -maths_results, -group, -program_knowledge, -schoolid)

X_vars <- c('hhh_gender', 'hhh_age', 'monthly_spending', 'hhh_literacy', 'age', 'gender', 'benef', 'school_spending', 'at_leisure', 'program_knowledge')
```

```{r}


baseline_guide <- read_excel('LCT Morroco/codebook_cct_baseline_18Feb2013_anon_en.dta.xlsx') %>% 
  t() %>%
  as.data.frame()

names(baseline_guide) <- baseline_guide[1,]
baseline_guide <- baseline_guide[-1,]

all_na <- function(x) sum(is.na(x)) == length(x)

set.seed(1)
```

# ATE analysis
## Treatment vs no treatment
```{r}
indiv_treat <- multi_arm_causal_forest (big_covars, morocco$maths_results, morocco$group %>% as.factor(),
  Y.hat = NULL , W.hat = NULL,
  num.trees = 10000,
  clusters = morocco$schoolid
  )

comprehension <- multi_arm_causal_forest (select(morocco, -hhid, -maths_results, -group), morocco$maths_results, morocco$group %>% as.factor(),
  Y.hat = indiv_treat$Y.hat, W.hat = indiv_treat$W.hat,
  num.trees = 10000,
  clusters = morocco$schoolid
  )

write_rds(indiv_treat, 'indiv_treat.rds')
```


# Figure 1

```{r}
indiv_ate <- average_treatment_effect(indiv_treat)
indiv_plots <- map(1:length(indiv_ate$contrast), function(x) {
  ate_est <- indiv_ate[x,][c("estimate", "std.err")] %>% unlist()
  preds <- indiv_treat$predictions[,x]
  qplot(x = preds) + 
    geom_vline(xintercept = 0, linetype = "dashed") +
    geom_vline(xintercept = ate_est['estimate'], color = "blue") +
    scale_y_continuous(limits = c(0, 600)) +
    annotate("rect", 
             xmin = ate_est['estimate'] - (1.96 * ate_est['std.err']), 
             xmax = ate_est['estimate'] + (1.96 * ate_est['std.err']), ymin = 0, ymax = Inf,
             alpha = .1,fill = "blue") +
    ggtitle("Contrast ", paste0(indiv_ate$contrast[x])) + 
    labs(x = "Predictions", y = "Counts")
})
save_plot('contrasts.png', cowplot::plot_grid(plotlist = indiv_plots), base_height = 5)
```

```{r}
# indiv_ate <- average_treatment_effect(comparison)
# indiv_plots <- map(1:length(indiv_ate$contrast), function(x) {
#   ate_est <- indiv_ate[x,][c("estimate", "std.err")] %>% unlist()
#   preds <- indiv_treat$predictions[,x]
#   qplot(x = preds) + 
#     geom_vline(xintercept = 0, linetype = "dashed") +
#     geom_vline(xintercept = ate_est['estimate'], color = "blue") +
#     scale_y_continuous(limits = c(0, 600)) +
#     annotate("rect", 
#              xmin = ate_est['estimate'] - (1.96 * ate_est['std.err']), 
#              xmax = ate_est['estimate'] + (1.96 * ate_est['std.err']), ymin = 0, ymax = Inf,
#              alpha = .1,fill = "blue") +
#     ggtitle("Contrast ", paste0(indiv_ate$contrast[x])) + 
#     labs(x = "Predictions", y = "Counts")
# })
# save_plot('contrasts1.png', cowplot::plot_grid(plotlist = indiv_plots), base_height = 5)
```
## Table

# Main analysis

## Auto selection
```{r}
get_labels <- function(x, source) {
  data.frame(label = sapply(source, attr,"label") %>% unlist()) %>%
    rownames_to_column() %>%
    right_join(x, by = c("rowname"= "name"))
}
```


```{r}
data.frame(name = names(select(morocco, -hhid, -maths_results, -group)), imp = variable_importance(comprehension)) %>%
  arrange(desc(imp)) %>%
  head(30) %>%
  ggplot(aes(x = reorder(name, imp), y = imp)) +
    geom_col() + 
    theme(axis.text.x = element_text(angle = 90)) +
    labs(x = "Variable", y = "Importance")

ggsave('comp_importance.png')
```

```{r}
data.frame(name = names(big_covars), imp = variable_importance(indiv_treat)) %>%
  arrange(desc(imp)) %>%
  head(30) %>%
  ggplot(aes(x = reorder(name, imp), y = imp)) +
    geom_col() + 
    theme(axis.text.x = element_text(angle = 90)) +
    labs(x = "Variable", y = "Importance")

ggsave('all_importance.png')
```

## Check ranking stability

```{r}
all_vars2 <- multi_arm_causal_forest (big_covars, morocco$maths_results, morocco$group %>% as.factor(),
  Y.hat = NULL , W.hat = NULL,
  num.trees = 10000,
  seed = 20
  )
```

```{r}
source("imp_variance.R")

imp_var <- get_imp_variance(big_covars, morocco$maths_results, morocco$group %>% as.factor(), 10, num_tree = 10000)
```

```{r}
imp_var[[1]]$names <- names(big_covars)
imp_var[[1]] %>%
  arrange(desc(mean_importances)) %>%
  select(names, mean_importances, std_importances, std_rnks) %>%
  head(20) %>%
  write_csv('var_imps.csv')
```


```{r}
data.frame(name = names(big_covars), imp = variable_importance(indiv_treat)) %>%
  left_join(select(imp_var$stats, names, std_rnks), by = c("name"= "names")) %>%
  mutate(std_std_rnks = std_rnks * 5.154579e-04) %>%
  get_labels(baseline) %>%
  arrange(desc(imp)) %>%
  head(20) %>%
  ggplot(aes(x = reorder(label %>% str_wrap(40), imp), y = imp)) +
    geom_col() + 
    theme(axis.text.x = element_text(angle = 90)) +
    labs(x = "Variable", y = "Importance") + 
    geom_point(aes(x = reorder(label %>% str_wrap(40), imp), y = std_std_rnks)) +
    scale_y_continuous(
    "Variable importance",
    sec.axis = sec_axis(~ . / 5.154579e-04, name = "Ranking standard deviation")
  )

ggsave('importances.png')
```

```{r}
school_time_use <- data.frame(
  indiv_treat$predictions,
  big_covars$c1_3_27_1
)

names(school_time_use) <- c("Treatment 1", "Treatment 2", "Treatment 3", "Time-use")

school_time_use %>%
  mutate(Activity = car::recode(`Time-use`,
                                "
                                11:19 = 'Personal care';
                                20:29 = 'Education';
                                30:59 = 'Domestic work';
                                60:79 = 'Non-domestic work';
                                80:89 = 'Leisure';
                                else = NA
                                "
                                )) %>%
  select(-`Time-use`) %>%
  gather(key = "Treatment", value = "Prediction", -Activity) %>%
  na.omit() %>%
  group_by(Activity, Treatment) %>%
  dplyr::summarise(Prediction = mean(Prediction)) %>%
  ggplot(aes(x = Activity, y = Prediction, fill = Treatment)) +
    geom_col(position = "dodge") +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

```


```{r}
# data.frame(name = names(big_covars), imp = variable_importance(all_vars),
#            rand_imp = variable_importance(randomised_cf),
#            first_letter = names(big_covars) %>% str_sub(start = 1, end = 1)) %>%
#   filter(str_detect(name, "^[:lower:][:digit:]")) %>%
#   group_by(first_letter) %>%
#   dplyr::summarise(
#     count = n(),
#     total_importance = sum(imp),
#     rand_importance = sum(rand_imp)
#   ) %>%
#   mutate(
#     portion_group = count / sum(count),
#     total_importance = total_importance / sum(total_importance)
#   ) %>%
#   select(-count) %>%
#   gather(key = "Measure", value = "Portion", -first_letter) %>%
#   ggplot(aes(x = reorder(first_letter, Portion), y = Portion, fill = Measure)) +
#     geom_col(position = "dodge")
# 
# ggsave('modules.png')
```



## Manual selection

```{r}
X_vars <- morocco %>% select(-group, -maths_results, -hhid) %>% names()
```


```{r}
indiv_treat = multi_arm_causal_forest (
  big_covars,
  morocco$maths_results, morocco$group %>% as.factor(),
  Y.hat = NULL , W.hat = NULL,
  num.trees = 10000,
  clusters = morocco$schoolid %>% as.factor()
  )

comprehension_model <- multi_arm_causal_forest (
  morocco %>% select(-hhid, maths_results),
  morocco$maths_results, morocco$group %>% as.factor(),
  Y.hat = indiv_treat$Y.hat , W.hat = indiv_treat$W.hat,
  num.trees = 10000,
  clusters = morocco$schoolid %>% as.factor()
  )

write_rds(indiv_treat, 'indiv_treat.rds')
```


```{r}
# code adapted from Athey et al. (2019)
# covars <- morocco2 %>% select(-any_drops, -group_cond, -hhid, age) %>% select_if(~ !all(is.na(.)))

names(big_covars) <- ifelse(names(big_covars) %in% row.names(baseline_guide), 
                        paste0(names(big_covars), baseline_guide[names(big_covars), "Dataset Label"]),
                        names(big_covars)
                        )
```


```{r}
data.frame(name = big_covars %>% names() %>% str_wrap(40), imp = variable_importance(indiv_treat)) %>%
  arrange(desc(imp)) %>% head(20) %>%
  ggplot(aes(x = reorder(name, imp), y = imp)) +
    geom_col() + 
    theme(axis.text.x = element_text(angle = 90))

ggsave('indiv_importance.png')
```


## Plot across values

```{r}
source('plot_het.R')
library(cowplot)
het_plots <- multi_outcome_plots(morocco[X_vars], indiv_treat$predictions, average_treatment_effect(indiv_treat)$estimate)

for (i in 1:length(het_plots)) {
  for (j in 1:length(het_plots[[i]])) {
    ggsave(paste0("results/varplot_", i, "-", j, ".png"), plot = het_plots[[i]][[j]], width = 4, height = 3)
  }
}
```

```{r}
set_x_1 <- morocco %>%
  select(starts_with('hhh_'), lack_program_knowledge) %>%
  names()

het_plots %>%
  unlist(recursive = F) %>%
  Filter(function (input) {input$labels$x %in% set_x_1}, .) %>%
  cowplot::plot_grid(plotlist = ., nrow = 3, ncol = length(set_x_1)) %>%
  save_plot("hhh_qualities.png", ., base_height = 5)

```

```{r}
set_x_2 <- c("age", "gender", "at_leisure")

het_plots %>%
  unlist(recursive = F) %>%
  Filter(function (input) {input$labels$x %in% set_x_2}, .) %>%
  cowplot::plot_grid(plotlist = ., nrow = 3, ncol = length(set_x_2)) %>%
  save_plot("individual_properties.png", ., base_height = 5)
```

```{r}
set_x_3 <- c("monthly_spending", "school_spending", "benef")

het_plots %>%
  unlist(recursive = F) %>%
  Filter(function (input) {input$labels$x %in% set_x_3}, .) %>%
  cowplot::plot_grid(plotlist = ., nrow = 3, ncol = length(set_x_3)) %>%
  save_plot("hh_qualities.png", ., base_height = 5)
```

```{r}
var_comparisons <- map(morocco[big_covars %>% names()], function(variable) {
  map(1: ncol(indiv_treat$predictions), function(treatment) {
    selector <- ifelse((variable %>% na.omit() %>% unique() %>% length()) == 2, max(variable, na.rm = T), median(variable, na.rm = T))
    list(
      low = average_treatment_effect(indiv_treat, subset = variable > selector),
      high = average_treatment_effect(indiv_treat, subset = variable <= selector)
    )
  })
})
```

```{r}
test_det(morocco %>% select(c(X_vars), lack_program_knowledge), indiv_treat$predictions) %>% bind_rows(.id = "contrast") %>% write_csv('t_tests.csv')
```

# Best linear projection

```{r}
binary_selector <- map(2:4, function(x) {
  selector <- indiv_treat$W.orig %in% c(1, x)
})
# 
# blps <- binary_forests(indiv_treat) %>%
#   map2(binary_selector, ~best_linear_projection(.x, .x$X.orig[c('hhh_gender', 'hhh_age', 'monthly_spending', 'hhh_literacy', 'age', 'gender', 'benef', 'school_spending')]))
```
# Maths results

```{r}
morocco %>% ggplot(aes(x = maths_results)) + geom_histogram(binwidth = 0.5) +
  theme_light() +
  labs(x = "Maths results (out of 4)", y = "Count")

ggsave("maths_results.png")
```

```{r}
pct_maths <- transmute(joined %>% filter(hhid %in% morocco$hhid),  division = (2-as.numeric(t6)), subtraction = (as.numeric(t5_2) / 2), num_recog = (as.numeric(t4_2) / 5), digit_recog = (as.numeric(t3_2) / 5)) %>%
  map_dbl(mean)

var_maths <- transmute(joined %>% filter(hhid %in% morocco$hhid),  division = (2-as.numeric(t6)), subtraction = (as.numeric(t5_2) / 2), num_recog = (as.numeric(t4_2) / 5), digit_recog = (as.numeric(t3_2) / 5)) %>%
  map_dbl(sd)

pct_maths %>%as.data.frame() %>% write.csv('maths_scores.csv')
```

# Time use

```{r}
assert_data <- morocco %>%
  mutate(activity = c1_3_21_1 %>% factor(levels = attributes(joined$c1_3_21_1)$labels, labels = names(attributes(joined$c1_3_21_1)$labels))) %>%
  bind_cols(indiv_treat$predictions) %>%
  select(starts_with("..."))

testit::assert(ncol(assert_data) == 3)

attributes(joined$c1_3_21_1)$labels %>% as.data.frame()

morocco %>%
  mutate(activity = c1_3_21_1 %>% factor(levels = attributes(joined$c1_3_21_1)$labels, labels = names(attributes(joined$c1_3_21_1)$labels))) %>%
  bind_cols(indiv_treat$predictions) %>%
  group_by(activity) %>%
  summarise(
    across(starts_with("..."), ~mean(., na.rm = TRUE), .names = "mean_{.col}"),
    first_digit = mean(c1_3_21_1, na.rm = T) %>% as.character() %>% substr(1,1),
    n1 = n()
  ) %>% write_csv('timeuse.csv')
```

